# This pipeline builds the sfpowerscripts plugin

name: 'Build Pipeline'

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'decision records/**'
      - 'demoreel/**'
      - 'prerequisites/**'

  workflow_dispatch:


jobs:
#Merge to Develop, Deploy Alpha builds
  alpha:
    name: 'Alpha'
    uses: ./.github/workflows/buildPackages.yml
    with:
      version: 'alpha'
      publish: true
      environment: alpha
    if: ${{ github.ref == 'refs/heads/develop' }}
    concurrency: alpha

# Hotfix stage
  hotfix:
    name: 'Hotfix'
    uses: ./.github/workflows/buildPackages.yml
    with:
      version: 'hotfix'
      publish: true
      environment: hotfix
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency: hotfix

  sfpowerscripts-beta:
    name: 'sfpowerscripts Beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfpowerscripts-cli/package.json'
      environment: beta
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  sfpowerscripts-prod:
    name: 'sfpowerscripts Prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfpowerscripts-cli/package.json'
      environment: prod
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [beta, hotfix]

  core-beta:
    name: 'core beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/core/package.json'
      environment: beta
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  core-prod:
    name: 'core prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/core/package.json'
      environment: prod
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [beta, hotfix]

  sfp-beta:
    name: 'sfp-cli beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: beta
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  sfp-prod:
    name: 'sfp-cli prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: prod
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [beta, hotfix]
